@echo off
set MATLAB=C:\Program Files\MATLAB\R2018a
"%MATLAB%\bin\win64\gmake" -f pwm_analysis.mk  COMBINE_OUTPUT_UPDATE_FCNS=0 INCLUDE_MDL_TERMINATE_FCN=1 MULTI_INSTANCE_CODE=0 ISPROTECTINGMODEL=NOTPROTECTING
