Ts = 1e-7; % sec
Tfinal = 2; % sec
Ripth = 0.3; % sec
minlim = 200; % V
maxlim = 340; % V
fsw = 10e3; % Hz
Vdc = 540; % Volts
Pout = 8e3; % W
Ef = 80; % Volts
Ls = 3.5e-3; % Henries
Rs = 1e-3; % Ohms
fout = 50; % Hz
wout = 2*pi*fout; % rad/sec
m = 3;
np = 2;
ns = 2;
n = ns*np;
Poutm = Pout/n; % Watts
Is = Poutm/(Ef*m); % amps
Xs = wout*Ls; % Ohms
Vdrop = Is*Xs; % Volts
Vt = sqrt(Ef^2+Vdrop^2); % Volts
Vdcm = Vdc/ns; % volts
ma = Vt*sqrt(3)/(Vdcm*0.612);
delta = acos(Ef/Vt); % radians
deltad = delta*180/pi; % degrees
pf = cos(delta);
phase = [0 0];
Rin = 50;
Lin = 1e-15;
Vinm = Vdcm + Rin*(Poutm*np/Vdcm);
Cdc1 = 5e-6; % F
Cdc = 3*Cdc1; % F
%ESL = 19e-9; % H
%ESR = 21.1e-3; % Ohm
ESL = 19e-15; % H
ESR = 21.1e-15; % Ohm
Lpar = 5e-15; % H
Rpar = 1e-15;


